// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfC2voFBIBFfBVVOF73ZqC5431l2JFxFw',
    appId: '1:637059358629:web:233488f068318e4ca4124c',
    messagingSenderId: '637059358629',
    projectId: 'taskapp-41167',
    authDomain: 'taskapp-41167.firebaseapp.com',
    storageBucket: 'taskapp-41167.firebasestorage.app',
    measurementId: 'G-EL2R1NGM1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXv5lWrXO-EYX87HKL_EBDiIi8or98H4Y',
    appId: '1:637059358629:android:80a78ca1ac425583a4124c',
    messagingSenderId: '637059358629',
    projectId: 'taskapp-41167',
    storageBucket: 'taskapp-41167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHw-mYWfAu1_jRcEvKXw-9TNswcAzyeys',
    appId: '1:637059358629:ios:753dfd4fadb2e18fa4124c',
    messagingSenderId: '637059358629',
    projectId: 'taskapp-41167',
    storageBucket: 'taskapp-41167.firebasestorage.app',
    iosBundleId: 'com.amisha.taskapp.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHw-mYWfAu1_jRcEvKXw-9TNswcAzyeys',
    appId: '1:637059358629:ios:753dfd4fadb2e18fa4124c',
    messagingSenderId: '637059358629',
    projectId: 'taskapp-41167',
    storageBucket: 'taskapp-41167.firebasestorage.app',
    iosBundleId: 'com.amisha.taskapp.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfC2voFBIBFfBVVOF73ZqC5431l2JFxFw',
    appId: '1:637059358629:web:a0b23a51159be5eea4124c',
    messagingSenderId: '637059358629',
    projectId: 'taskapp-41167',
    authDomain: 'taskapp-41167.firebaseapp.com',
    storageBucket: 'taskapp-41167.firebasestorage.app',
    measurementId: 'G-5XPKJLFQGW',
  );

}