name: Build Flutter Web and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Enable web support
        run: flutter config --enable-web

      - name: Navigate to Flutter project directory
        run: cd .  # Replace with e.g. `cd Task_App` if needed

      - name: Install dependencies
        run: |
          cd .  # Replace if project is not at root
          flutter pub get

      - name: Build Flutter web
        run: |
          cd .  # Replace if project is not at root
          flutter build web

      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: deploy
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
