name: Build Flutter Web and Deploy to GitHub Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'   # ✅ This includes Dart 3.5.4
          channel: 'stable'
          cache: true

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: |
          cd task_app/task_app
          flutter pub get

      - name: Build Flutter web
        run: |
          cd task_app/task_app
          flutter build web

      - name: Deploy to GitHub deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: task_app/task_app/build/web
          publish_branch: deploy
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
