name: Build Flutter Web and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Flutter (latest stable) and set PATH
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: |
          cd task_app/task_app
          flutter pub get

      - name: Build Flutter web
        run: |
          cd task_app/task_app
          flutter build web

      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: task_app/task_app/build/web
          publish_branch: deploy
